### ISSUE TITLE
Handle configurations better

### ISSUE THREAD

**Issue by shaz13-socgen** [shaz13/katana#48]
Current configurations is very naive. Hard to configure. Must refactor before v1

**Comment by AdityaSoni19031997** [comment]
>Current configurations is very naive. Hard to configure. Must refactor before v1

Is there something specific that's troubling?

**Comment by shaz13-socgen** [comment]
Yes, there are constants at config.yml, config.py, and random constants in main.py. 

Also looking forward to move all logging config to a yaml file. Do we need .conf?

It would be better if we can leverage logs in Debug mode as well and not only with gunicorn instance. 

+ Logging levels is hard to config. Need to make it more easy and simple

**Comment by AdityaSoni19031997** [comment]
Thanks for the detailed response. I will try converting it to *.yml. IMO
*.conf gives you more control and easier to set-up in a straightforward way
and it's one of the recommend way as per docs as well.

Regarding constants, some assumptions are always made wrt SRC design,
right? Otherwise to circumvent it, you either have to give them as user
input while invoking the snips or use them as env variables. Not sure if it
can be auto-setup/automated completely... Will look into it!
